const FETCHED_RECOMMENDED_MOVIES = 'FETCHED_RECOMMENDED_MOVIES'
const LOADING = 'LOADING_RECOMMENDED_MOVIES'
const FETCHED_SEARCHED_MOVIES = 'FETCHING_SEARCHED_MOVIES'
const LOGIN_USER = "LOGIN_USER"
const ADD_TO_WATCH_LIST = 'ADD_TO_WATCH_LIST'

export { FETCHED_RECOMMENDED_MOVIES, LOADING, FETCHED_SEARCHED_MOVIES, LOGIN_USER, ADD_TO_WATCH_LIST }