const FETCHED_RECOMMENDED_MOVIES = 'FETCHED_RECOMMENDED_MOVIES'
const LOADING = 'LOADING_RECOMMENDED_MOVIES'
const FETCHED_SEARCHED_MOVIES = 'FETCHING_SEARCHED_MOVIES'
const NEW_USER_PERSISTED = "NEW_USER_PERSISTED"

export { FETCHED_RECOMMENDED_MOVIES, LOADING, FETCHED_SEARCHED_MOVIES, NEW_USER_PERSISTED }